kind: pipeline
type: docker 
name: deploy_dev
node:
  environment: ryali
trigger:
  branch:
  - main

steps:
- name: build and deploy
  image: node:latest
  commands:
    - npm install
    - npm run build
    - rm -rf /dazzle/*
    - mv ./build/* /dazzle/
---
kind: pipeline
type: docker 
name: deploy_prod
node:
  environment: ryali
trigger:
  event:
  - tag

steps:
- name: build and deploy
  image: node:latest
  commands:
    - npm install
    - npm run build
    - rm -rf /dazzle/*
    - mv ./build/* /dazzle/
