kind: pipeline
type: docker
name: default

steps:
  - name: build_deploy
    privileged: true
    image: node:latest
    volumes:
      - name: dazzle
        path: /home/light/dazzle/:/dazzle
    commands:
      # - npm install
      # - npm run build
      - pwd
      - ls .
      - ls ..
      - ls /
      - ls /drone
      - ls /drone/*
      - ls /home/
      - cp -r ./build/* /dazzle/
      - ls /dazzle/
      - cat /dazzle/index.html
