kind: pipeline
type: docker 
name: deploy_dev

trigger:
  branch:
  - main

steps:
- name: build
  image: node:latest
  commands:
    - npm install
    - npm run build

- name: deploy
  image: byteflair/scp
  commands:
    - ssh -t 'light@5.75.206.84' 'rm -rf /home/light/dazzle_dev/*'
    - mv ./build ./dazzle_dev
    - scp -t -r './dazzle_dev/' 'light@5.75.206.84:/home/light/'
    - ssh -t 'light@5.75.206.84' 'chmod -R 755 /home/light/dazzle_dev/'

---
kind: pipeline
type: docker 
name: deploy_prod

trigger:
  event:
  - tag

steps:
- name: build
  image: node:latest
  commands:
    - npm install
    - npm run build

- name: deploy
  image: byteflair/scp
  commands: 
    - ssh 'light@5.75.206.84' 'rm -rf /home/light/dazzle/*'
    - mv ./build ./dazzle/
    - scp -r './dazzle/' 'light@5.75.206.84:/home/light/'

