kind: pipeline
type: docker
name: default

steps:
  - name: build_deploy
    privileged: true
    image: node:latest
    commands:
      - npm install
      - npm run build
      - cp -r ./build/* /dazzle/
